### ISSUE TITLE
Issue with Media Wiki? No links

### ISSUE THREAD

**Issue by brh55** [WikiDiggly/Diggly-Back-End#10]
https://en.wikipedia.org/wiki/MediaWiki

Maybe nothing that relevant?

**Comment by akshayinbox** [comment]
Idk what you're referring to. Works fine on my end:
![image](https://cloud.githubusercontent.com/assets/6697976/14712792/89ca00d8-07ac-11e6-904d-c069bd52ec15.png)

I searched for "MediaWiki" and clicked the same suggestion.

**Comment by akshayinbox** [comment]
Closed due to failure to duplicate the issue. Perhaps, a client-side caching issue.
